"use client";
import React from "react";
import "./globals.css";
import { Poppins } from "next/font/google";
import { ChakraProvider } from "@chakra-ui/react";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const poppins = Poppins({
	subsets: ["latin"],
	style: ["normal", "italic"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	display: "swap",
});

// export const metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={poppins.className}>
			<body>
				<ChakraProvider>
					<Navbar />
					{children}
					<Footer />
				</ChakraProvider>
			</body>
		</html>
	);
}
