"use client";
import React from "react";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

import "@fontsource/poppins/400.css";
import "@fontsource/poppins/700.css";
import theme from "./theme";

// export const metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<ChakraProvider theme={theme}>
					<Navbar />
					{children}
					<Footer />
				</ChakraProvider>
			</body>
		</html>
	);
}
