"use client";

import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import { CacheProvider } from "@emotion/react";

import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

import "@fontsource/poppins/400.css";
import "@fontsource/poppins/700.css";
import theme from "./theme";
import { HydrationProvider, Client } from "react-hydration-provider";

// export const metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<HydrationProvider>
					<Client>
						<CacheProvider>
							<ChakraProvider theme={theme}>
								<Navbar />
								{children}
								<Footer />
							</ChakraProvider>
						</CacheProvider>
					</Client>
				</HydrationProvider>
			</body>
		</html>
	);
}
